# Generated by Django 4.0.4 on 2022-09-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_games_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='download',
            field=models.URLField(default=1, max_length=500000),
            preserve_default=False,
        ),
    ]
